version: "3"
services:
  web:
    build: .
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    restart: always
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: "destinationdiary.globa.one"
      LETSENCRYPT_HOST: "destinationdiary.globa.one"

networks:
  default:
    external:
      name: proxy
