services:
  web:
    build: .
    container_name: destination-diary
    restart: unless-stopped
    environment:
      NODE_ENV: production
    labels:
      com.centurylinklabs.watchtower.enable: false

networks:
  default:
    name: proxy
    external: true
